// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5oKqp0yK3oljBdyVFk7EPL5E4vto3Ycw',
    appId: '1:872126391062:web:32558aabf5c7f1c797e637',
    messagingSenderId: '872126391062',
    projectId: 'waterburg-safaris',
    authDomain: 'waterburg-safaris.firebaseapp.com',
    storageBucket: 'waterburg-safaris.appspot.com',
    measurementId: 'G-ET66VBFHLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALG8rLM0r7RewmmISgQ9dy51b7e35Ap9Y',
    appId: '1:872126391062:android:07faaf0fb5a40ca997e637',
    messagingSenderId: '872126391062',
    projectId: 'waterburg-safaris',
    storageBucket: 'waterburg-safaris.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCITen5eqKZmyOrn4N_XnbEL43xs8mOmWk',
    appId: '1:872126391062:ios:ba4e159f4747149e97e637',
    messagingSenderId: '872126391062',
    projectId: 'waterburg-safaris',
    storageBucket: 'waterburg-safaris.appspot.com',
    iosClientId: '872126391062-33i0hohmh3ei2kig6ja9ofp40mpugood.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCITen5eqKZmyOrn4N_XnbEL43xs8mOmWk',
    appId: '1:872126391062:ios:ba4e159f4747149e97e637',
    messagingSenderId: '872126391062',
    projectId: 'waterburg-safaris',
    storageBucket: 'waterburg-safaris.appspot.com',
    iosClientId: '872126391062-33i0hohmh3ei2kig6ja9ofp40mpugood.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
